# Use an official Node.js runtime as a parent image
FROM amd64/nginx:alpine
# Copy the built app from the previous stage
COPY /build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]