name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build_test:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x, 15.x]

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
        - name: npm ci, build and test
          run: |
            npm ci
            npm run build --if-present
            npm test    

  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: carl0222/recipes_frontend_amd64:latest